// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: WallLightRemote_DSM

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_DSMInitScreen
void ui_DSMInitScreen_screen_init(void);
lv_obj_t * ui_DSMInitScreen;
lv_obj_t * ui_DSMInitImage;
lv_obj_t * ui_DSMVersionLabel;
lv_obj_t * ui_DSMDateLabel;

// SCREEN: ui_DSMMainScreen
void ui_DSMMainScreen_screen_init(void);
lv_obj_t * ui_DSMMainScreen;
lv_obj_t * ui_DSMTopBar1;
lv_obj_t * ui_DSMTestLabel1;
lv_obj_t * ui_DSMSpinner1;
lv_obj_t * ui_DSMButton1;
lv_obj_t * ui_DSMButtonLabel1;
lv_obj_t * ui_BarVu;
lv_obj_t * ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_DSMInitScreen_screen_init();
    ui_DSMMainScreen_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_DSMInitScreen);
}
