// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel2 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel2, 98);
    lv_obj_set_height(ui_Panel2, 41);
    lv_obj_set_x(ui_Panel2, -26);
    lv_obj_set_y(ui_Panel2, -57);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_SCROLLABLE);     /// Flags
    lv_obj_set_scrollbar_mode(ui_Panel2, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_radius(ui_Panel2, 9, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel2, lv_color_hex(0x3D3D3D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel2, lv_color_hex(0xFF4200), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelId = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_labelId, 75);
    lv_obj_set_height(ui_labelId, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelId, 7);
    lv_obj_set_y(ui_labelId, -52);
    lv_obj_set_align(ui_labelId, LV_ALIGN_LEFT_MID);
    lv_label_set_long_mode(ui_labelId, LV_LABEL_LONG_CLIP);
    lv_label_set_text(ui_labelId, "ID: 1012");
    lv_obj_clear_flag(ui_labelId, LV_OBJ_FLAG_CLICK_FOCUSABLE);      /// Flags
    lv_obj_set_style_text_color(ui_labelId, lv_color_hex(0xFF4200), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelId, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelId, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelValue = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_labelValue, lv_pct(100));
    lv_obj_set_height(ui_labelValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_labelValue, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_labelValue, LV_LABEL_LONG_CLIP);
    lv_label_set_text(ui_labelValue, "14.25");
    lv_obj_set_style_text_color(ui_labelValue, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_labelValue, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelValue, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel1 = lv_obj_create(ui_Screen1);
    lv_obj_set_height(ui_Panel1, 27);
    lv_obj_set_width(ui_Panel1, lv_pct(100));
    lv_obj_set_x(ui_Panel1, 0);
    lv_obj_set_y(ui_Panel1, 50);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_SCROLLABLE);     /// Flags
    lv_obj_set_scrollbar_mode(ui_Panel1, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_radius(ui_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0x3D3D3D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel1, lv_color_hex(0xC4C4C4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Panel1, LV_BORDER_SIDE_TOP, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelStep = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_labelStep, lv_pct(90));
    lv_obj_set_height(ui_labelStep, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelStep, 0);
    lv_obj_set_y(ui_labelStep, 51);
    lv_obj_set_align(ui_labelStep, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelStep, "Step: 0.01");
    lv_obj_set_style_text_color(ui_labelStep, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelStep, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelStep, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

}
