// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: WallLightRemote_DSA

#ifndef _WALLLIGHTREMOTE_DSA_UI_H
#define _WALLLIGHTREMOTE_DSA_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "../../lib/lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_DSAMainScreen
void ui_DSAMainScreen_screen_init(void);
extern lv_obj_t * ui_DSAMainScreen;
extern lv_obj_t * ui_DSAIdPanel;
extern lv_obj_t * ui_DSALabelId;
extern lv_obj_t * ui_DSALabelValue;
extern lv_obj_t * ui_DSABottomPanel;
extern lv_obj_t * ui_DSALabelStep;
extern lv_obj_t * ui____initial_actions0;

void ui_init_dsa(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
