// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: WallLightRemote_DSA

#include "../ui.h"

void ui_DSAMainScreen_screen_init(void)
{
    ui_DSAMainScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_DSAMainScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_DSAIdPanel = lv_obj_create(ui_DSAMainScreen);
    lv_obj_set_width(ui_DSAIdPanel, 98);
    lv_obj_set_height(ui_DSAIdPanel, 41);
    lv_obj_set_x(ui_DSAIdPanel, -26);
    lv_obj_set_y(ui_DSAIdPanel, -57);
    lv_obj_set_align(ui_DSAIdPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_DSAIdPanel, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_SCROLLABLE);     /// Flags
    lv_obj_set_scrollbar_mode(ui_DSAIdPanel, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_radius(ui_DSAIdPanel, 9, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_DSAIdPanel, lv_color_hex(0x3D3D3D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DSAIdPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_DSAIdPanel, lv_color_hex(0xFF4200), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_DSAIdPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DSALabelId = lv_label_create(ui_DSAMainScreen);
    lv_obj_set_width(ui_DSALabelId, 75);
    lv_obj_set_height(ui_DSALabelId, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DSALabelId, 7);
    lv_obj_set_y(ui_DSALabelId, -52);
    lv_obj_set_align(ui_DSALabelId, LV_ALIGN_LEFT_MID);
    lv_label_set_long_mode(ui_DSALabelId, LV_LABEL_LONG_CLIP);
    lv_label_set_text(ui_DSALabelId, "ID: 1000");
    lv_obj_clear_flag(ui_DSALabelId, LV_OBJ_FLAG_CLICK_FOCUSABLE);      /// Flags
    lv_obj_set_style_text_color(ui_DSALabelId, lv_color_hex(0xFF4200), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DSALabelId, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DSALabelId, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DSALabelValue = lv_label_create(ui_DSAMainScreen);
    lv_obj_set_width(ui_DSALabelValue, lv_pct(100));
    lv_obj_set_height(ui_DSALabelValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_DSALabelValue, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_DSALabelValue, LV_LABEL_LONG_CLIP);
    lv_label_set_text(ui_DSALabelValue, "0.0");
    lv_obj_set_style_text_color(ui_DSALabelValue, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DSALabelValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_DSALabelValue, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DSALabelValue, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DSABottomPanel = lv_obj_create(ui_DSAMainScreen);
    lv_obj_set_height(ui_DSABottomPanel, 27);
    lv_obj_set_width(ui_DSABottomPanel, lv_pct(100));
    lv_obj_set_x(ui_DSABottomPanel, 0);
    lv_obj_set_y(ui_DSABottomPanel, 50);
    lv_obj_set_align(ui_DSABottomPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_DSABottomPanel,
                      LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SCROLLABLE);     /// Flags
    lv_obj_set_scrollbar_mode(ui_DSABottomPanel, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_radius(ui_DSABottomPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_DSABottomPanel, lv_color_hex(0x3D3D3D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DSABottomPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_DSABottomPanel, lv_color_hex(0xC4C4C4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_DSABottomPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_DSABottomPanel, LV_BORDER_SIDE_TOP, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DSALabelStep = lv_label_create(ui_DSAMainScreen);
    lv_obj_set_width(ui_DSALabelStep, lv_pct(90));
    lv_obj_set_height(ui_DSALabelStep, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DSALabelStep, 0);
    lv_obj_set_y(ui_DSALabelStep, 51);
    lv_obj_set_align(ui_DSALabelStep, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DSALabelStep, "Step: 0.1");
    lv_obj_set_style_text_color(ui_DSALabelStep, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DSALabelStep, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DSALabelStep, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

}
